export const categories = [
  {
    id: "remonti",
    slug: "remonti",
    name: "Ремонти и майстори",
    nameEn: "Repairs & Handymen",
    description: "ВиК, електро, боядисване и довършителни ремонти",
    icon: "/images/categories/stroitelstvo.png",
    color: "#FF6B6B",
    subcategories: [
      { id: "vik", name: "ВиК и канализация", slug: "vik", icon: "🔧" },
      { id: "elektro", name: "Електроинсталации и осветление", slug: "elektro", icon: "⚡" },
      { id: "boyadisvane", name: "Боядисване и шпакловане", slug: "boyadisvane", icon: "🎨" },
      { id: "gipsokarton", name: "Гипсокартон и сухо строителство", slug: "gipsokarton", icon: "🪚" },
      { id: "podovi-nastilki", name: "Подови настилки (ламинат, паркет, теракот)", slug: "podovi-nastilki", icon: "🪵" },
      { id: "klyucharski", name: "Ключарски услуги", slug: "klyucharski", icon: "🔑" },
      { id: "dovarshitelni-remonti", name: "Довършителни ремонти", slug: "dovarshitelni-remonti", icon: "🏠" },
      { id: "drebni-remonti-dom", name: "Дребни ремонти в дома", slug: "drebni-remonti-dom", icon: "🔨" },
      { id: "remont-banya-kuhnya", name: "Ремонт на баня и кухня", slug: "remont-banya-kuhnya", icon: "🚿" },
      { id: "klimatici-montaj", name: "Инсталация на климатици", slug: "klimatici-montaj", icon: "❄️" },
    ],
  },
  {
    id: "pochistvane",
    slug: "pochistvane",
    name: "Почистване",
    nameEn: "Cleaning",
    description: "Домашно, основно и офис почистване",
    icon: "/images/categories/pochistvane.png",
    color: "#27AE60",
    subcategories: [
      { id: "domashno", name: "Почистване на дом", slug: "domashno", icon: "🧹" },
      { id: "ofis-targovski", name: "Почистване на офис и търговски обекти", slug: "ofis-targovski", icon: "🏢" },
      { id: "sled-remont", name: "Почистване след ремонт", slug: "sled-remont", icon: "🧽" },
      { id: "prozortsi-fasadi", name: "Почистване на прозорци и фасади", slug: "prozortsi-fasadi", icon: "🪟" },
      { id: "tapicerii-kilimi", name: "Почистване на тапицерии и килими", slug: "tapicerii-kilimi", icon: "🛋️" },
      { id: "generalno", name: "Генерално почистване", slug: "generalno", icon: "✨" },
      { id: "imoti-napuskane", name: "Почистване на имоти след напускане", slug: "imoti-napuskane", icon: "📦" },
      { id: "avto-detailing", name: "Авто почистване и детайлинг", slug: "avto-detailing", icon: "🚗" },
      { id: "gruming", name: "Груминг за домашни любимци", slug: "gruming", icon: "🐾" },
    ],
  },
  {
    id: "montaj",
    slug: "montaj",
    name: "Монтаж и дребни услуги",
    nameEn: "Assembly & Small Jobs",
    description: "Мебели, техника, хамали и дребни ремонти",
    icon: "/images/categories/mebeli.png",
    color: "#8E44AD",
    subcategories: [
      { id: "mebeli", name: "Монтаж на мебели (IKEA, JYSK и др.)", slug: "mebeli", icon: "🪑" },
      { id: "bitova-tehnika", name: "Монтаж на битова техника", slug: "bitova-tehnika", icon: "🍳" },
      { id: "premestvane-hamali", name: "Хамалски услуги и преместване", slug: "premestvane-hamali", icon: "🚛" },
      { id: "vrati-prozortsi-shtori", name: "Монтаж на врати, прозорци и щори", slug: "vrati-prozortsi-shtori", icon: "🚪" },
      { id: "garderob-kuhnya", name: "Сглобяване на гардероби и кухни", slug: "garderob-kuhnya", icon: "🗄️" },
      { id: "drebni-bitovi", name: "Дребни битови услуги (рафтове, картини, корнизи)", slug: "drebni-bitovi", icon: "🔩" },
      { id: "elektro-osvetlenie", name: "Монтаж на осветление и електроуреди", slug: "elektro-osvetlenie", icon: "💡" },
    ],
  },
  {
    id: "gradina",
    slug: "gradina",
    name: "Градина и двор",
    nameEn: "Garden & Yard",
    description: "Косене, поддръжка и озеленяване",
    icon: "/images/categories/gradina.png",
    color: "#2ECC71",
    subcategories: [
      { id: "kosene", name: "Косене и поддръжка на трева", slug: "kosene", icon: "🌱" },
      { id: "podryazvane", name: "Подрязване на дървета и храсти", slug: "podryazvane", icon: "✂️" },
      { id: "ozelenyavane", name: "Озеленяване и цветни лехи", slug: "ozelenyavane", icon: "🌿" },
      { id: "pochistvane-dvor", name: "Почистване на двор и тераса", slug: "pochistvane-dvor", icon: "🍂" },
      { id: "aleyi", name: "Изграждане и поддръжка на алеи", slug: "aleyi", icon: "🏡" },
      { id: "baseini", name: "Поддръжка на басейни и външни пространства", slug: "baseini", icon: "🏊" },
    ],
  },
]

export const homepageBanners = [
  {
    title: "Провери профили на специалисти в твоя район",
    description: "Разгледай верифицирани майстори и услуги близо до теб.",
    cta: "Виж специалисти",
    href: "/bg/specialists",
    image: "/images/banners/specialists.jpg",
  },
  {
    title: "Стани специалист в ProZona",
    description: "Създай профил и получавай запитвания от клиенти.",
    cta: "Създай профил",
    href: "/bg/become-specialist",
    image: "/images/banners/become-specialist.jpg",
  },
]

export const homepageHero = {
  title: "Намери верифициран специалист близо до теб",
  subtitle: "Ремонти, почистване, монтаж и градински услуги на едно място.",
  searchPlaceholder: "Каква услуга търсите?",
  cta: "Намери специалист",
}

export const cities = [
  "София",
  "Пловдив",
  "Варна",
  "Бургас",
  "Русе",
  "Стара Загора",
  "Плевен",
  "Видин",
  "Велико Търново",
  "Благоевград",
  "Перник",
  "Хасково",
  "Ямбол",
  "Пазарджик",
  "Добрич",
  "Шумен",
  "Сливен",
  "Враца",
  "Габрово",
  "Кърджали",
]