export const categories = [
  {
    id: "remonti",
    slug: "remonti",
    name: "Ремонти и майстори",
    nameEn: "Repairs & Handymen",
    description: "ВиК, електро, боядисване и довършителни ремонти",
    icon: "/images/categories/stroitelstvo.png",
    color: "#FF6B6B",
    subcategories: [
      { id: "vik", name: "ВиК услуги", slug: "vik", icon: "🔧" },
      { id: "elektro", name: "Електро услуги", slug: "elektro", icon: "⚡" },
      { id: "boyadisvane", name: "Боядисване", slug: "boyadisvane", icon: "🎨" },
      { id: "shpaklovka-zidariya", name: "Шпакловка и зидария", slug: "shpaklovka-zidariya", icon: "🧱" },
      { id: "remont-banya", name: "Ремонт на баня", slug: "remont-banya", icon: "🚿" },
      { id: "gipsokarton", name: "Гипсокартон", slug: "gipsokarton", icon: "🪚" },
      { id: "dovarshitelni-remonti", name: "Довършителни ремонти", slug: "dovarshitelni-remonti", icon: "🏠" },
    ],
  },
  {
    id: "pochistvane",
    slug: "pochistvane",
    name: "Почистване",
    nameEn: "Cleaning",
    description: "Домашно, основно и офис почистване",
    icon: "/images/categories/pochistvane.png",
    color: "#27AE60",
    subcategories: [
      { id: "domashno", name: "Домашно почистване", slug: "domashno", icon: "🧼" },
      { id: "osnovno", name: "Основно почистване", slug: "osnovno", icon: "✨" },
      { id: "sled-remont", name: "Почистване след ремонт", slug: "sled-remont", icon: "🧹" },
      { id: "ofis", name: "Офис почистване", slug: "ofis", icon: "🏢" },
      { id: "naem", name: "Почистване при смяна на наематели", slug: "naem", icon: "📦" },
    ],
  },
  {
    id: "montaj",
    slug: "montaj",
    name: "Монтаж и дребни услуги",
    nameEn: "Assembly & Small Jobs",
    description: "Мебели, техника, хамали и дребни ремонти",
    icon: "/images/categories/mebeli.png",
    color: "#8E44AD",
    subcategories: [
      { id: "mebeli", name: "Монтаж на мебели", slug: "mebeli", icon: "🪑" },
      { id: "klimatici", name: "Монтаж, профилактика и ремонт на климатици", slug: "klimatici", icon: "❄️" },
      { id: "osvetlenie", name: "Монтаж на осветление", slug: "osvetlenie", icon: "💡" },
      { id: "elektrouredi", name: "Монтаж на електроуреди", slug: "elektrouredi", icon: "🔌" },
      { id: "drebni-remonti", name: "Дребни домашни ремонти", slug: "drebni-remonti", icon: "🔨" },
      { id: "premestvane-hamali", name: "Преместване на мебели и хамалски услуги", slug: "premestvane-hamali", icon: "🚚" },
    ],
  },
  {
    id: "gradina",
    slug: "gradina",
    name: "Градина и двор",
    nameEn: "Garden & Yard",
    description: "Косене, поддръжка и озеленяване",
    icon: "/images/categories/gradina.png",
    color: "#2ECC71",
    subcategories: [
      { id: "kosene", name: "Косене на трева", slug: "kosene", icon: "🌱" },
      { id: "poddrazhka-dvor", name: "Поддръжка на двор", slug: "poddrazhka-dvor", icon: "🏡" },
      { id: "podryazvane", name: "Подрязване на дървета", slug: "podryazvane", icon: "✂️" },
      { id: "ozelenyavane", name: "Озеленяване", slug: "ozelenyavane", icon: "🌿" },
      { id: "pochistvane-dvor", name: "Почистване на двор", slug: "pochistvane-dvor", icon: "🍂" },
    ],
  },
]

export const homepageBanners = [
  {
    title: "Провери профили на специалисти в твоя район",
    description: "Разгледай верифицирани майстори и услуги близо до теб.",
    cta: "Виж специалисти",
    href: "/bg/specialists",
    image: "/images/banners/specialists.jpg",
  },
  {
    title: "Стани специалист в ProZona",
    description: "Създай профил и получавай запитвания от клиенти.",
    cta: "Създай профил",
    href: "/bg/become-specialist",
    image: "/images/banners/become-specialist.jpg",
  },
]

export const homepageHero = {
  title: "Намери верифициран специалист близо до теб",
  subtitle: "Ремонти, почистване, монтаж и градински услуги на едно място.",
  searchPlaceholder: "Каква услуга търсите?",
  cta: "Намери специалист",
}

export const cities = [
  "София",
  "Пловдив",
  "Варна",
  "Бургас",
  "Русе",
  "Стара Загора",
  "Плевен",
  "Видин",
  "Велико Търново",
  "Благоевград",
  "Перник",
  "Хасково",
  "Ямбол",
  "Пазарджик",
  "Добрич",
  "Шумен",
  "Сливен",
  "Враца",
  "Габрово",
  "Кърджали",
]
