export const categories = [
  {
    id: "remonti-i-stroitelstvo-new",
    slug: "remonti-i-stroitelstvo-new",
    name: "Ремонти и строителство",
    nameEn: "Repairs & Construction",
    description: "ВиК, електро, шпакловка, покриви и всички ремонти",
    icon: "/images/categories/stroitelstvo.png",
    color: "#FF6B6B",
    subcategories: [
      { id: "vik-new", name: "ВиК", slug: "vik-new", icon: "🔧" },
      { id: "elektro-new", name: "Електро", slug: "elektro-new", icon: "⚡" },
      { id: "shpaklovka-boyadisvane-new", name: "Шпакловка и боядисване", slug: "shpaklovka-boyadisvane-new", icon: "🎨" },
      { id: "gipsokarton-new", name: "Гипсокартон", slug: "gipsokarton-new", icon: "🪚" },
      { id: "remont-pokrivi-new", name: "Ремонт на покриви", slug: "remont-pokrivi-new", icon: "🏚️" },
      { id: "remont-banya-new", name: "Ремонт на баня", slug: "remont-banya-new", icon: "🚿" },
      { id: "podovi-nastilki-new", name: "Подови настилки", slug: "podovi-nastilki-new", icon: "🪵" },
      { id: "drebni-remonti-new", name: "Дребни ремонти", slug: "drebni-remonti-new", icon: "🔨" },
      { id: "kartene-sabarane-new", name: "Къртене и събаряне", slug: "kartene-sabarane-new", icon: "⛏️" },
      { id: "izvozване-otpadaci-new", name: "Извозване на строителни отпадъци", slug: "izvozване-otpadaci-new", icon: "🚛" },
    ],
  },
  {
    id: "pochistvane-new",
    slug: "pochistvane-new",
    name: "Почистване",
    nameEn: "Cleaning",
    description: "Домашно, офис и генерално почистване",
    icon: "/images/categories/pochistvane.png",
    color: "#27AE60",
    subcategories: [
      { id: "domashno-pochistvane-new", name: "Домашно почистване", slug: "domashno-pochistvane-new", icon: "🧹" },
      { id: "sled-remont-new", name: "Почистване след ремонт", slug: "sled-remont-new", icon: "🧽" },
      { id: "ofis-pochistvane-new", name: "Почистване на офиси", slug: "ofis-pochistvane-new", icon: "🏢" },
      { id: "generalno-pochistvane-new", name: "Генерално почистване", slug: "generalno-pochistvane-new", icon: "✨" },
    ],
  },
  {
    id: "transport-hamali-new",
    slug: "transport-hamali-new",
    name: "Транспорт и хамали",
    nameEn: "Transport & Movers",
    description: "Хамалски услуги, преместване и транспорт",
    icon: "/images/categories/transport.png",
    color: "#3498DB",
    subcategories: [
      { id: "hamali-new", name: "Хамалски услуги", slug: "hamali-new", icon: "💪" },
      { id: "premestvane-new", name: "Преместване на дома/офис", slug: "premestvane-new", icon: "📦" },
      { id: "transport-new", name: "Транспортни услуги", slug: "transport-new", icon: "🚛" },
      { id: "patna-pomosht-new", name: "Пътна помощ", slug: "patna-pomosht-new", icon: "🚗" },
    ],
  },
  {
    id: "uroci-i-obuchenie",
    slug: "uroci-i-obuchenie",
    name: "Уроци и обучение",
    nameEn: "Tutoring & Education",
    description: "Частни уроци, подготовка за изпити и курсове",
    icon: "/images/categories/uroci.png",
    color: "#F39C12",
    subcategories: [
      { id: "matematika", name: "Математика", slug: "matematika", icon: "📐" },
      { id: "ezikovo-obuchenie", name: "Езиково обучение", slug: "ezikovo-obuchenie", icon: "🌍" },
      { id: "balgarski-ezik-i-literatura", name: "Български език и литература", slug: "balgarski-ezik-i-literatura", icon: "📖" },
      { id: "fizika-i-himiya", name: "Физика и химия", slug: "fizika-i-himiya", icon: "🧪" },
      { id: "programirane", name: "Програмиране", slug: "programirane", icon: "💻" },
      { id: "muzikalni-instrumenti", name: "Музикални инструменти", slug: "muzikalni-instrumenti", icon: "🎹" },
      { id: "podgotovka-za-maturi", name: "Подготовка за матури и кандидатстване", slug: "podgotovka-za-maturi", icon: "🎓" },
    ],
  },
  {
    id: "klimatici-new",
    slug: "klimatici-new",
    name: "Климатици",
    nameEn: "Air Conditioning",
    description: "Монтаж, демонтаж и сервиз на климатици",
    icon: "/images/categories/klimatici.png",
    color: "#00BCD4",
    subcategories: [
      { id: "montaj-demontaj-klimatik-new", name: "Монтаж и демонтаж", slug: "montaj-demontaj-klimatik-new", icon: "❄️" },
      { id: "servis-klimatik-new", name: "Сервиз и профилактика", slug: "servis-klimatik-new", icon: "🔧" },
    ],
  },
  {
    id: "mebeli-interior-new",
    slug: "mebeli-interior-new",
    name: "Мебели и интериор",
    nameEn: "Furniture & Interior",
    description: "Монтаж и изработка на мебели",
    icon: "/images/categories/mebeli.png",
    color: "#8E44AD",
    subcategories: [
      { id: "montaj-mebeli-new", name: "Монтаж на мебели", slug: "montaj-mebeli-new", icon: "🪑" },
      { id: "izrabotka-mebeli-new", name: "Изработка по поръчка", slug: "izrabotka-mebeli-new", icon: "🪚" },
      { id: "vrati-prozortsi-new", name: "Монтаж на врати и прозорци", slug: "vrati-prozortsi-new", icon: "🚪" },
    ],
  },
  {
    id: "gradina-dvor-new",
    slug: "gradina-dvor-new",
    name: "Градина и двор",
    nameEn: "Garden & Yard",
    description: "Косене, озеленяване и поддръжка",
    icon: "/images/categories/gradina.png",
    color: "#2ECC71",
    subcategories: [
      { id: "kosene-new", name: "Косене на трева", slug: "kosene-new", icon: "🌱" },
      { id: "ozelenyavane-new", name: "Озеленяване", slug: "ozelenyavane-new", icon: "🌿" },
      { id: "podryazvane-new", name: "Подрязване на дървета", slug: "podryazvane-new", icon: "✂️" },
      { id: "pochistvane-dvor-new", name: "Почистване на двор", slug: "pochistvane-dvor-new", icon: "🍂" },
    ],
  },
  {
    id: "avto-uslugi-new",
    slug: "avto-uslugi-new",
    name: "Авто услуги",
    nameEn: "Auto Services",
    description: "Автосервиз, автомивка и ГТП",
    icon: "/images/categories/avto.png",
    color: "#E74C3C",
    subcategories: [
      { id: "avtoservis-new", name: "Автосервиз", slug: "avtoservis-new", icon: "🔧" },
      { id: "avtomivka-new", name: "Автомивка", slug: "avtomivka-new", icon: "🚿" },
      { id: "gtp-new", name: "ГТП", slug: "gtp-new", icon: "📋" },
      { id: "avto-detailing-new", name: "Авто детайлинг, полиране и керамична защита", slug: "avto-detailing-new", icon: "✨" },
    ],
  },
  {
    id: "it-kompyutri-new",
    slug: "it-kompyutri-new",
    name: "IT и компютри",
    nameEn: "IT & Computers",
    description: "Ремонт на компютри и IT услуги",
    icon: "/images/categories/it.png",
    color: "#1ABC9C",
    subcategories: [
      { id: "remont-kompyutri-new", name: "Ремонт на компютри", slug: "remont-kompyutri-new", icon: "💻" },
      { id: "mreji-internet-new", name: "Мрежи и интернет", slug: "mreji-internet-new", icon: "🌐" },
    ],
  },
  {
    id: "krasota-zdrave-new",
    slug: "krasota-zdrave-new",
    name: "Красота и здраве",
    nameEn: "Beauty & Health",
    description: "Фризьори, маникюристи, масажисти и фитнес",
    icon: "/images/categories/krasota.png",
    color: "#FF69B4",
    subcategories: [
      { id: "frizyor-new", name: "Фризьори", slug: "frizyor-new", icon: "💇" },
      { id: "manikyur-new", name: "Маникюристи", slug: "manikyur-new", icon: "💅" },
      { id: "masaj-new", name: "Масажисти", slug: "masaj-new", icon: "💆" },
      { id: "fitnes-new", name: "Фитнес салони", slug: "fitnes-new", icon: "💪" },
    ],
  },
]

export const homepageBanners = [
  {
    title: "Провери профили на специалисти в твоя район",
    description: "Разгледай верифицирани майстори и услуги близо до теб.",
    cta: "Виж специалисти",
    href: "/bg/specialists",
    image: "/images/banners/specialists.jpg",
  },
  {
    title: "Стани специалист в ProZona",
    description: "Създай профил и получавай запитвания от клиенти.",
    cta: "Създай профил",
    href: "/bg/become-specialist",
    image: "/images/banners/become-specialist.jpg",
  },
]

export const homepageHero = {
  title: "Намери верифициран специалист близо до теб",
  subtitle: "Ремонти, почистване, монтаж и градински услуги на едно място.",
  searchPlaceholder: "Каква услуга търсите?",
  cta: "Намери специалист",
}

export const cities = [
  "София",
  "Пловдив",
  "Варна",
  "Бургас",
  "Русе",
  "Стара Загора",
  "Плевен",
  "Видин",
  "Велико Търново",
  "Благоевград",
  "Перник",
  "Хасково",
  "Ямбол",
  "Пазарджик",
  "Добрич",
  "Шумен",
  "Сливен",
  "Враца",
  "Габрово",
  "Кърджали",
]